### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by Ak4zh** [alefiori82/amazon-paapi5#2]
[ERROR/2020-03-03 04:18:14,870] root: (ApiException)
Reason: {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.es/paapi5/documentation/sending-request.html#signing."}]}

My device timezone is UTC.
Accessing Spain (ES) marketplace.

**Comment by alefiori82** [comment]
I tried to access to spain marketplace and I did not get any problem in get results. Please verify that you pass the credentials correctly. For Spain the country parameter should be set to ES. The marketplace is automatically set by the library.

**Comment by Ak4zh** [comment]
Sorry it works now.
The keys had the problem.
For anyone experiencing this in future, the above problem can arise due to incorrect secret or a missed character in aws secret.
Amazon will not give invalid keys warning rather say InvalidSignatureException if your aws secret is incorrect.

**Comment by enea1982** [comment]
guys to me from this mistake can you help me   

Status code: 401
Errors : {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}
Request ID: 
INFO:root:'NoneType' object is not iterable
Error calling PA-API 5.0!
Status code: 401
Errors : {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}
Request ID:b
INFO:root:'NoneType' object is not iterable

**Comment by image-karthik** [comment]
Yes same error me also, anyone suggest the solutions please
